apiVersion: v1
kind: Service
metadata:
  name: {{ include "gf-auth-server.fullname" . }}
  labels:
    {{- include "gf-auth-server.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  clusterIP: {{ .Values.service.clusterIP }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http

  selector:
    {{- include "gf-auth-server.selectorLabels" . | nindent 4 }}
